var DATA = {
	menu: ['home', 'photos', 'resume', 'games'],
	splash: [
		{photo: 'splash2.jpg', desc: 'Paris'},
		{photo: 'splash3.jpg', desc: 'Rockefeller Center'},
		{photo: 'splash4.jpg', desc: 'Salt Lake City'},
		{photo: 'splash5.jpg', desc: 'Vail Ski Resort'},
		{photo: 'splash6.jpg', desc: 'Jackson, Wy'},
		{photo: 'splash7.jpg', desc: 'Denver'},
		{photo: 'splash8.jpg', desc: 'Lake Placid'},
		{photo: 'splash9.jpg', desc: 'Niagara Falls'},
		{photo: 'splash10.jpg', desc: 'Lake Tahoe'}
	],
	quotes : [
		{quote: 'Success is never permanent. Failure is never failure. The only thing that really counts is to never, never, never give up', auth: 'Sir Winston Churchill'},
		{quote: 'I\'m a finisher in a society of starters...I have this vision that is constantly evolving in my head'},
		{quote: 'A wise man will be Master of His Mind; A Fool will be Its Slave', auth: 'Publilius Syrus'},
		{quote: 'Man is what he thinks all day long', auth: 'Ralph Waldo Emerson'},
		{quote: 'Great spirits have always encountered violent opposition from mediocre minds', auth: 'Albert Einstein'},
		{quote: 'Sow a thought, reap an act.  Sow an act, reap a habit.  Sow a habit, reap a character.  Sow a character, reap an eternal destiny', auth: 'David O McKay'},
		{quote: 'I\'ve been poor and I\'ve been rich.  I must say, it is much better to be rich', auth: 'Tom Hanks'},
		{quote: 'There is a story of the Buddha who has a reputation for being peaceful and nonviolent regardless of what he encountered in life.  A man heard of this Buddha and decided to test him.  He would be rude and obnoxious to him.  He criticized him and verbally abused the Buddha.  But the Buddha responded with love and kindness.  How could you be so peaceful and kind when all I\'ve ever said to you was antagonistic?  The Buddha replies, \"If someone offers you a gift, and you do not accept the gift, to whom does the gift belong?\"  If someone offers you a gift of anger or hostility and you do not accept it, then it still belongs to the giver.  Why choose to be upset and angry over something that does not belong to you?'},
		{quote: 'Be Impeccable with your word...Don\'t take anything personally...Don\'t make assumptions...Always do your best', auth: 'Don Miguel Ruiz'},
		{quote: 'Life\'s a journey, not a destination', auth: 'Aerosmith'},
		{quote: 'Now and then I go about pitying myself and all the while my soul is being blown by great winds across the sky', auth: '[Ojibway Native]'},
		{quote: 'Two roads diverged in a wood, and I--I took the one less traveled by, and that has made all the difference', auth: 'Robert Frost'},
		{quote: 'It makes no sense to worry about the things you have no control over, because if you have no control over them, it makes no sense to worry about them.  It makes no sense to worry about the things you have control over, because if you have control, it makes no sense to worry.  And there goes everything it is possible to worry about'},
		{quote: 'Man is not the creature of circumstances.  Circumstances are the creatures of men', auth: 'Benjamin Disraeli'},
		{quote: 'The best is yet to come', auth: 'Def Leppard'},
		{quote: 'If you can only see that success is inevitable and waiting for you, you will not delay a second more to seize it', auth: 'SW'},
		{quote: 'When you are dead, seek for your resting place not in the earth, but in the hearts of men', auth: 'Rumi'},
		{quote: 'Not having a clear vision of what I wanted...I just started saying I wanted what everyone else wanted.  Looking back, I realize this was my biggest mistake', auth: 'Margaret Cho'},
		{quote: 'Be positive at all times.  If you expect to fail, you will.  Before the battle begins, make sure you expect to win - then there will be no battle for you will have won before it starts', auth: 'Sun Tzu'},
		{quote: 'Rule Number One: Never lose money. Rule Number Two: Never forget Rule Number One', auth: 'Warren E Buffett'},
		{quote: 'Some of us may be born with a greater or lesser degree of each of these traits than others.  However, I believe all of us can \"grow\" our capabilities in each of these areas if we discipline ourselves and make the effort', auth: 'Philip A Fisher'},
		{quote: 'There is nothing either good or bad, but thinking makes it so', auth: 'William Shakespeare'},
		{quote: 'Hatred is never ended by hatred but by love', auth: 'Buddha'},
		{quote: 'Be wiser than other people if you can; but do not tell them so', auth: 'Lord Chesterfield'},
		{quote: 'I judge people by their own principles - not by my own', auth: 'Martin Luther King, Jr'},
		{quote: 'As tough as times get, the key to success is to carry on as if these are the good old days', auth: 'Donald J Trump'},
		{quote: 'Nearly everyone on the Forbes 400 list of richest Americans falls into one of three categories: entrepreneurs, buy-and-hold investors, and those who inherited their money. Only a couple of market-timers and technical investors are on the list, and there are no day traders', auth: 'Mark A Sellers, Morningstar'},
		{quote: 'If you really want to do something you will do it', auth: '[Anonymous Brother]'},
		{quote: 'Miss your train?  Another one is coming...'},
		{quote: 'With great power comes great responsibility', auth: 'Sir Winston Churchill'},
		{quote: 'I construct an airtight box.  I keep inside it what I want to think about, and everything else stays beyond the walls.  Inside is white, outside is black...Inside is love and friends and optimism.  Outside is negativity, can\'t-doism, and any criticism of me and mine.', auth: 'Virginia Kelley'},
		{quote: 'Unlimited...together we\'re unlimited; together we\'ll be the greatest team there\'s ever been...', auth: 'Elphaba'},
		{quote: 'The greatest enemy of knowledge is not ignorance - it is the illusion of knowledge', auth: 'Stephen Hawking'},
		{quote: 'Work smarter, not harder', auth: 'Scrooge McDuck'},
		{quote: 'When all you have is a hammer, everything in life looks like a nail', auth: 'Abraham Maslow'},
		{quote: 'Life is too important to take too seriously', auth: '[Anonymous]'},
		{quote: 'I don\'t know the key to success, but I know the key to failure - trying to please everyone', auth: ''},
		{quote: 'Whatever you can do, or dream you can, begin it.  Boldness has genius, power, and magic in it', auth: 'Goethe'},
		{quote: 'I can calculate the motions of the heavenly bodies, but not the madness of people', auth: 'Sir Isaac Newton'},
		{quote: 'We have met the enemy, and he is us', auth: 'Walt Kelly'},
		{quote: 'Put all your eggs in one basket - and watch that basket', auth: 'Mark Twain'},
		{quote: 'The intellect should be the servant of the heart, but not its slave', auth: 'Comte'},
		{quote: 'A horse that can count to ten is a remarkable horse - not a remarkable mathematician', auth: 'Samuel Johnson'},
		{quote: 'Too much of a good thing can be wonderful', auth: 'Mae West'},
		{quote: 'I\'m no genius, I\'m smart in spots - but I stay around those spots', auth: 'Thomas J Watson Sr'},
		{quote: 'Overall, we\'ve done better by avoiding dragons than by slaying them', auth: 'Warren E Buffett'},
		{quote: 'Most men would rather die than think.  Many do', auth: 'Bertrand Russell'},
		{quote: 'Go to where the puck is going to be, not to where it is', auth: 'Wayne Gretzky'},
		{quote: 'Men are disturbed not by things but by the principles and notions which they form concerning things', auth: 'Epictetus'},
		{quote: 'Nearly all the best things that came to me in life have been unexpected, unplanned by me', auth: 'Carl Sandburg'},
		{quote: 'Failure is the opportunity to begin again, more intelligently', auth: 'Henry Ford'},
		{quote: 'Oh, God, to reach the point of death only to realize you have never lived', auth: 'Henry David Thoreau'},
		{quote: 'Chance favors the mind that\'s prepared', auth: 'Louis Pasteur'},
		{quote: 'If you can meet with Triumph and Disaster and treat these two imposters just the same...', auth: 'Rudyard Kipling'},
		{quote: 'We must embrace pain and burn it as fuel for our journey', auth: 'Kenji Miyazawa'},
		{quote: 'Ultimate excellence lies not in winning every battle, but in defeating the enemy without ever fighting', auth: 'Sun Tzu'},
		{quote: 'Some men are born great, some men achieve greatness, and some men have greatness thrust upon them', auth: 'Shakespeare'},
		{quote: 'Each time I find myself laying flat on my face, I just pick myself up and get back in the race', auth: 'Dean Kay & Kelly Gordon'},
		{quote: 'I am Ripper... Tearer... Slasher... Gouger. I am the Teeth in the Darkness, the Talons in the Night. Mine is Strength... and Lust... and Power! I AM BEOWULF!', auth: 'Beowulf'},
		{quote: 'If we die... it will be for GLORY, not gold', auth: 'Beowulf'},
		{quote: 'The sound of a martini being shaken by an able barkeep, ice clattering like gravel in a frosty crucible, is the siren\'s song guiding tired souls on a long day\'s journey into night', auth: 'Eno Putain'},
		{quote: 'The best way to predict the future is to invent it', auth: 'Alan Kay'},
		{quote: 'My future starts when I wake up every morning.  Every day I find something creative to do with my life', auth: 'Miles Davis'},
		{quote: 'A foolish faith in authority is the worst enemy of truth', auth: 'Albert Einstein'},
		{quote: 'In the simplest terms, a leader is one who knows where he wants to go, and gets up, and goes', auth: 'John Erskine'},
		{quote: 'The key insight that I have reached is recognition of the inherent fallibility of human thought', auth: 'George Soros'},
		{quote: '...not everything goes to plan...life can take the strangest turns...things can happen that you wouldn\'t imagine in your wildest dreams', auth: 'Boris Becker'},
		{quote: 'Once you go down that road, you can\'t stop', auth: 'Bernie Madoff'},
		{quote: 'I live, I love, I slay, and I\'m content', auth: 'Conan the Barbarian'},
		{quote: 'I was hoping he would get up so I could hit him again and keep him down', auth: 'Mike Tyson'},
		{quote: 'I\'m a dreamer. I have to dream and reach for the stars, and if I miss a star then I grab a handful of clouds', auth: 'Mike Tyson'},
		{quote: 'In the end, it\'s not the years in your life that count. It\'s the life in your years', auth: 'Abraham Lincoln'},
		{quote: 'It has been my experience that folks who have no vices have very few virtues', auth: 'Abraham Lincoln'},
		{quote: 'It is better to remain silent and be thought a fool than to open one\'s mouth and remove all doubt', auth: 'Abraham Lincoln'},
		{quote: 'Most folks are as happy as they make up their minds to be', auth: 'Abraham Lincoln'},
		{quote: 'Nearly all men can stand adversity, but if you want to test a man\'s character, give him power', auth: 'Abraham Lincoln'},
		{quote: 'No man has a good enough memory to be a successful liar', auth: 'Abraham Lincoln'},
		{quote: 'Tact is the ability to describe others as they see themselves', auth: 'Abraham Lincoln'},
		{quote: 'That some achieve great success, is proof to all that others can achieve it as well', auth: 'Abraham Lincoln'},
		{quote: 'We should be too big to take offense and too noble to give it', auth: 'Abraham Lincoln'},
		{quote: 'When I am getting ready to reason with a man, I spend one-third of my time thinking about myself and what I am going to say and two-thirds about him and what he is going to say', auth: 'Abraham Lincoln'},
		{quote: 'Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky', auth: 'Rabindranath Tagore'},
		{quote: 'Hope is a waking dream', auth: 'Aristotle'},
		{quote: 'Only the educated are free', auth: 'Epictetus'},
		{quote: 'The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence', auth: 'Confucius'},
		{quote: 'The wise does at once what the fool does at last', auth: 'Baltasar Gracian'},
		{quote: 'To be a good loser is to learn how to win', auth: 'Carl Sandburg'},
		{quote: 'True happiness involves the full use of one\'s power and talents', auth: 'John W. Gardner'},
		{quote: 'What is called genius is the abundance of life and health', auth: 'Henry David Thoreau'},
		{quote: 'What you do today can improve all your tomorrows', auth: 'Ralph Marston'},
		{quote: 'All life is an experiment. The more experiments you make the better', auth: 'Ralph Waldo Emerson'},
		{quote: 'Every man dies. Not every man really lives', auth: 'William Wallace'},
		{quote: 'I think I\'ve discovered the secret of life - you just hang around until you get used to it', auth: 'Charles M. Schulz'},
		{quote: 'Never be bullied into silence. Never allow yourself to be made a victim. Accept no one\'s definition of your life; define yourself', auth: 'Harvey Fierstein'},
		{quote: 'The great use of life is to spend it for something that will outlast it', auth: 'William James'},
		{quote: 'The price of anything is the amount of life you exchange for it', auth: 'Henry David Thoreau'},
		{quote: 'What we play is life', auth: 'Louis Armstrong'},
		{quote: 'It\'s the game of life. Do I win or do I lose? One day they\'re gonna shut the game down. I gotta have as much fun and go around the board as many times as I can before it\'s my turn to leave', auth: 'Tupac Shakur'}, 
		{quote: 'Reality is wrong. Dreams are for real', auth: 'Tupac Shakur'},
		{quote: 'We\'re having too good a time today. We ain\'t thinking about tomorrow', auth: 'John Dillinger'},
		{quote: 'Are you not entertained?', auth: 'Maximus Decimus Meridius'},		
		{quote: 'It is my eternal goal to always improve myself and radiate peace wherever I go', auth: 'SW'}		
	],
	photos: [
		{photo: 'nyu.jpg', desc: 'My good friend Steve and I at our NYU graduation.'},
		{photo: 'lasvegas.jpg', desc: 'Post-graduation break at Las Vegas.'},
		{photo: 'tennis.jpg', desc: 'I\'ve been playing tennis since I was 13 years old.'},
		{photo: 'ski.jpg', desc: 'Skiing at Gore Mountain, 1997.'},
		{photo: 'hotpot.jpg', desc: 'Got together with some new friends I met at the Gore Mountain ski trip for hotpot and games, Winter 1998.'},
		{photo: 'karaoke.jpg', desc: 'I like to sing karaoke, esp Ah lun\'s songs. &nbsp;Here we are at Binny\'s, Spring 1998.'},
		{photo: 'fish.jpg', desc: 'I went fishing a couple of times. &nbsp;Everytime I went I vowed never to go again because the boat is so noisy and you get salt all over your body. &nbsp;But here I am again for the 3rd time, Fall 1998.'},
		{photo: 'asiadecuba.jpg', desc: 'I enjoy dining at fine restaurants. &nbsp;Here we are at Asia de Cuba by the Morgan Hotel after a reservation 4 weeks in advance.'},
		{photo: 'carmines.jpg', desc: 'Ah, my favorite pasttime: eating. &nbsp;Here we are at the famous Carmine\'s in Times Square.'},
		{photo: 'virginia.jpg', desc: 'Since I don\'t play anymore, I just watch. &nbsp;Here I am at the Chase Championships at MSG, Dec 1998.'},
		{photo: 'lobster.jpg', desc: 'Here I am with a 2 lb Lobster.'},
		{photo: 'bmw.jpg', desc: 'Cruis\'in down the highway at nite.'},
		{photo: 'china.jpg', desc: 'Guangzhou, July 1999.'},
		{photo: 'hangzhou.jpg', desc: 'Hangzhou, the most beautiful city in China.'},
		{photo: 'longisland.jpg', desc: 'Long Island Sound, Fall 1999. &nbsp;Antidote for stress.'},
		{photo: 'skimtn.jpg', desc: 'The 2000-2001 ski season was absolutely the best. &nbsp;Skiing every week. &nbsp;Here is a view from top of a diamond slope at Belleayre.'},
		{photo: 'sky.jpg', desc: 'Skydiving at the Poconos, Summer 2001.'},
		{photo: 'wedding.jpg', desc: 'Co-worker\'s wedding banquet, Fall 2001.'},
		{photo: 'comedy.jpg', desc: 'One of my dreams is to do stand-up comedy. &nbsp;I\'m very proud to do it again for my 5th time at Gramercy, July 2002.'},
		{photo: 'locals.jpg', desc: 'BBQ at Prospect Park, Summer 2002.'},
		{photo: 'onefamily.jpg', desc: 'On the set of <i>One Family One Child One Door</i>, Fall 2002.'},
		{photo: 'thirdwatch.jpg', desc: 'On the scorching hot set of <i>Third Watch</i>, NBC, Summer 2003.'},
		{photo: 'prom.jpg', desc: 'At <i>The Awesome 80s Prom</i>, Webster Hall, Fall 2004.'},
		{photo: 'fung.jpg', desc: 'Audience members having a ball with Fung Schwey at <i>The Awesome 80s Prom</i>, Webster Hall, Fall 2004.'},
		{photo: 'janewedding.jpg', desc: 'Old friends and new friends at a friend\'s wedding, Flushing, Fall 2004.'},
		{photo: 'dandme.jpg', desc: 'My beautiful date and I at my friend\'s wedding, Flushing, Fall 2004.'},
		{photo: 'bride.jpg', desc: 'My beautiful date (left) and the lovely bride (right), Flushing, Fall 2004.'},
		{photo: 'toronto.jpg', desc: 'Waiting for my connecting flight to Vancouver and then to BC. &nbsp; Toronto, Canada, Winter 2005.'},
		{photo: 'whistler.jpg', desc: 'On top of Whistler Mountain. &nbsp;Nothing like fresh, brisk mountain air....ahhh! BC, Canada, Winter 2005.'},
		{photo: 'zip.jpg', desc: 'Ziplining over Fitzsimmons Creek, BC, Canada, Winter 2005.'},
		{photo: 'kensington.jpg', desc: 'I\'m not in NY anymore...Kensington, London, UK, Spring 2005.'},
		{photo: 'underground.jpg', desc: 'Above ground on the Underground, London, UK, Spring 2005.'},
		{photo: 'londoneye.jpg', desc: 'At the London Eye, London.'},
		{photo: 'ivywedding.jpg', desc: 'Ah, reunited again, Fall 2005.'},
		{photo: 'ivy.jpg', desc: 'The beautiful bride and I, Fall 2005.'},
		{photo: 'jfk.jpg', desc: 'JFK Airport. &nbsp;Waiting for a flight to...'},
		{photo: 'paris.jpg', desc: '...Ah, Paris. &nbsp;Fall 2005.'},
		{photo: 'seine.jpg', desc: 'The tranquil River Seine, Paris, France.'},
		{photo: 'pedrera.jpg', desc: 'On top of La Pedrera by Gaudi, Barcelona, Spain, Fall 2005.'},
		{photo: 'guell.jpg', desc: 'Park Guell by Gaudi, Barcelona.'},
		{photo: 'valencia.jpg', desc: 'Check out this cool railroad station, Valencia, Spain, Fall 2005.'},
		{photo: 'vell.jpg', desc: 'Chill\'in at Port Vell, Barcelona.'},
		{photo: 'mill.jpg', desc: 'Ah, nothing like a cold beer in a good ol fashion tavern after a tiresome day of skiing. &nbsp;Here we are at the Grist Mill in Killington, Vermont, December 2005.'},
		{photo: 'benjerry.jpg', desc: 'What do you do when it rains during your ski vacation? &nbsp;Why, visit the famous Ben &amp Jerry Ice Cream Factory in Waterbury, Vermont, of course!'},
		{photo: 'kpeak.jpg', desc: 'Enjoying the tasty food on top of Killington Peak, March 2006.'},
		{photo: 'mandywedding.jpg', desc: 'The groom, myself, and the beautiful bride, Summer 2006.'},
		{photo: 'danwedding.jpg', desc: 'Me and Da Danster.  His wedding, Fall 2006.'},
		{photo: 'tremblant.jpg', desc: 'The beautiful Riviere du Diable at Mont Tremblant, Quebec, Winter 2007.'},
		{photo: 'vt_house.jpg', desc: 'Weekend house in Vermont, Winter 2007.'},
		{photo: 'biketour.jpg', desc: 'Huff\'in and puff\'in at the 30th Five Boro Bike Tour, May 2007.'},
		{photo: 'raft.jpg', desc: 'Ah, 3rd time is a charm.  I was able to stay on the raft this time unlike the rest of the crew, Pa, May 2007.'},
		{photo: 'mtb.jpg', desc: 'Mountain Biking in Pa, Spring 2007.'},
		{photo: 'coors.jpg', desc: 'Good times at the Coors Brewery at Golden, Co, Winter 2008.'},
		{photo: 'vail.jpg', desc: 'Hanging out wid my gf at Vail, Winter 2008.'},
		{photo: 'vailgroup.jpg', desc: 'The whole gang at Vail Village, Winter 2008.'},
		{photo: 'skivail.jpg', desc: 'Awesome skiing gets in your blood, Vail, Winter 2008.'},
		{photo: 'skivailclose.jpg', desc: 'Awesome skiing gets in your blood!, Vail, Winter 2008.'},
		{photo: 'crv.jpg', desc: 'Winter wonderland, Catskills, Winter 2009.'},
		{photo: 'alta.jpg', desc: 'Alta is for skiers only, Alta, Utah, March 2009.'},
		{photo: 'solitude.jpg', desc: 'Enroute to Honeycomb Basin, Solitude, Utah, March 2009.'},
		{photo: 'tunnel.jpg', desc: 'Inside tunnel to Mineral Basin, Snowbird, Utah, March 2009.'},
		{photo: 'tunnelout.jpg', desc: 'Outside tunnel in Mineral Basin, Snowbird, Utah, March 2009.'},
		{photo: 'snowbird.jpg', desc: 'Beautiful Rockies, Snowbird, Utah, March 2009.'},
		{photo: 'tdtour.jpg', desc: 'Showing my racing stripes at the Five Boro Bike Tour, May 2009.'},
		{photo: 'jetblue.jpg', desc: 'Going nowhwere..., Summer 2009.'},
		{photo: 'posse.jpg', desc: 'My posse, August 2009.'},
		{photo: 'break.jpg', desc: 'Best Man takes a break, August 2009.'},
		{photo: 'speech.jpg', desc: 'Best Man gives funnie speech, but wedding couple is not amused, August 2009.'},
		{photo: 'babble.jpg', desc: 'Babble, April 2010.'},
		{photo: 'southbeach.jpg', desc: 'South Beach, baby!, Summer 2010.'},
		{photo: 'glades.jpg', desc: 'Cruis\'in on an airboat, Everglades, Summer 2010.'},
		{photo: 'rail.jpg', desc: 'Riding the Swiss Rail, Winter 2011.'},
		{photo: 'zermatt.jpg', desc: 'Here I am at the beautiful ski village in Zermatt, Switzerland, Winter 2011.'},
		{photo: 'matterhorn.jpg', desc: 'Breathtaking view of the famous Matterhorn Peak, Winter 2011.'},
		{photo: 'gondola.jpg', desc: 'Enroute to the top of Zermatt Mountain, more than 12,000ft above sea level, Winter 2011.'},
		{photo: 'geneva.jpg', desc: 'Returning home from Geneva Airport, Winter 2011.'},
		{photo: 'masa.jpg', desc: 'Here I am, behind the sushi counter with the chef.  No, he\'s not Chef Masa, but he was pretty good.  My favorite dishes were the Kobe beef w/truffle and grilled unagi roll, Fall 2011.'},
		{photo: 'jh.jpg', desc: 'Jackson Hole Ski Resort, Wy, Winter 2012.'},
		{photo: 'idaho.jpg', desc: 'Winter in Idaho, 2012.'},
		{photo: 'snowmobile.jpg', desc: 'Need for speed at Teton National Forest, Wyoming, Winter 2012.'},
		{photo: 'jackson.jpg', desc: 'Chill\'in in Jackson, Wy, Winter 2012.'},
		{photo: 'tahoe.jpg', desc: 'Beautiful Lake Tahoe, Ca, Winter 2013.'},
		{photo: 'tahoe_bench.jpg', desc: 'Reflecting...Lake Tahoe, Ca, Winter 2013.'},
		{photo: 'tahoe_woods.jpg', desc: 'Revelation!'},
		{photo: 'tahoe_cabin.jpg', desc: 'Illusions of grandeur.'},
		{photo: 'fran.jpg', desc: 'Start of epic New England trip, Winter 2013.'},
		{photo: 'ac.jpg', desc: 'AC days, Summer 2013.'},
		{photo: 'ms.jpg', desc: 'Work-oriented, 2014.'},
		{photo: 'porsche.jpg', desc: 'Chill\'in in my fave car, Spring 2015.'},
		{photo: 'track.jpg', desc: 'Beautiful day for tracking, Spring 2015.'},
		{photo: 'la.jpg', desc: 'Enjoying the scene at Venice Beach, Summer 2015.'},
		{photo: 'usopen.jpg', desc: 'At the US Open with my new friends, Fall 2015.'},
		{photo: 'ariana.jpg', desc: 'Ariana in concert, Fall 2015.'},
		{photo: 'lambo.jpg', desc: '2015 was a fun year.'},
		{photo: 'killie.jpg', desc: 'Back to Killington, Winter 2016.'},
		{photo: 'ohare.jpg', desc: 'Returning home from a most interesting trip to Chicago, O\'Hare Airport, Spring 2016.'},
		{photo: 'bacon.jpg', desc: 'Hanging out in midtown eating thick-cut bacon, Wolfgang\'s, May 2016.'},
		{photo: 'bny.jpg', desc: 'Ahhh...taking a breath, just chill\'in, and enjoying the view, Summer 2016.'},
		{photo: 'usopen2.jpg', desc: 'Enjoying early rounds at the Open, Fall 2016.'},
		{photo: 'pokemon.png', desc: 'Playing Pokemon Go before my trip..., Fall 2016.'},
		{photo: 'vegas2.jpg', desc: '...Back to Vegas, Fall 2016.'},
		{photo: 'grandcanyon.jpg', desc: 'Beautiful View of the Grand Canyon, Fall 2016.'},
		{photo: 'newark.jpg', desc: 'End of fun Vegas trip, Newark Airport, Fall 2016.'},
		{photo: 'mohegan.jpg', desc: 'Chill\'in in my 2nd home, Winter 2017.'},
		{photo: 'blackandtan.jpg', desc: 'Enjoying a cold one at my trusty bar, Spring 2017.'},
		{photo: 'office.jpg', desc: 'Wow, finally getting my own office, Summer 2017.'},
		{photo: 'limo.jpg', desc: 'Here\'s to you and the good life.'}
	],
	games: [
		{
			cat: 'Games',
			items: [
				{name: 'Tic-tac-toe', url: 'ttt.html', desc: 'A two-levels tic-tac-toe game with computer AI'},
				{name: 'Blackjack', url: 'blkjk.html', desc: 'A simple blackjack game with Canvas images'},
				{name: 'Battleship', url: 'btlshp.html', desc: 'Battleship game with auto ship placement, computer AI, and simulation'},
				{name: 'Ski', url: 'ski.html', desc: 'Multi-levels ski and ride game with surprise final round'},
				{name: 'Tetris', url: 'tetris.html', desc: 'Fully Canvas-based game with an object-oriented design using Factory design pattern'},
				{name: 'Blackjack Deluxe', url: 'blackjack-deluxe.html', desc: 'Fully custom decks and functional blackjack using flexbox and es6'},
				{name: 'Pac-man', url: 'pacman.html', desc: 'Pac-man using CSS3 animations and es6'}
			]
		},
		{
			cat: 'Sims',
			items: [
				{name: 'Monopoly', url: 'mono.html', desc: 'Fully customizable simulation done in pure SVG in a MVC framework'},
				{name: 'Baseball', url: 'baseball.html', desc: 'Customizable baseball teams simulation'}
			]
		}
	]
};














